/**
 * Client-side mirror of server/lib/migratedVoucherGuard.ts — detects vouchers
 * the server refuses to mutate, so the UI can disable edit/delete actions and
 * show a lock badge instead of offering an action that will come back 403.
 *
 * Two classes are protected:
 *  - records copied in read-only mode by the GC-LSHI migration tool, and
 *  - vouchers generated by the Golden Coast accounting programme, which are
 *    idempotency-tracked and corrected by reversal rather than by editing.
 */
export type GuardedVoucher = { voucherNumber?: string | null; sourceModule?: string | null };

export function isReadonlyMigratedVoucher(voucher: GuardedVoucher) {
  if (!voucher) return false;
  if (voucher.sourceModule === "SP_MIGRATION_READONLY") return true;
  if (voucher.voucherNumber && voucher.voucherNumber.startsWith("MIG-")) return true;
  return false;
}

export function isGoldenCoastProgrammeVoucher(voucher: GuardedVoucher) {
  if (!voucher) return false;
  return Boolean(voucher.voucherNumber && voucher.voucherNumber.startsWith("GC-"));
}

/** True when no client action may mutate this voucher. */
export function isVoucherMutationBlocked(voucher: GuardedVoucher) {
  return isReadonlyMigratedVoucher(voucher) || isGoldenCoastProgrammeVoucher(voucher);
}

/** Short label for the lock badge, or null when the voucher is editable. */
export function voucherLockLabel(voucher: GuardedVoucher): string | null {
  if (isReadonlyMigratedVoucher(voucher)) return "Read-only migration";
  if (isGoldenCoastProgrammeVoucher(voucher)) return "Golden Coast posting";
  return null;
}
