/**
 * Client-side mirror of server/lib/migratedVoucherGuard.ts — detects vouchers
 * the server refuses to mutate, so the UI can disable edit/delete actions and
 * show a lock badge instead of offering an action that will come back 403.
 *
 * Two classes are protected:
 *  - records copied in read-only mode by the GC-LSHI migration tool, and
 *  - vouchers generated by the Golden Coast accounting programme, which are
 *    idempotency-tracked and corrected by reversal rather than by editing.
 *
 * Golden Coast POS cash-transfer journals are the narrow exception for delete:
 * their dedicated server lifecycle removes both sides of the intercompany cash
 * movement together. Editing those journals is still blocked by the programme
 * guard and by the Daybook edit predicate.
 */
export type GuardedVoucher = { voucherNumber?: string | null; sourceModule?: string | null };

export function isReadonlyMigratedVoucher(voucher: GuardedVoucher) {
  if (!voucher) return false;
  if (voucher.sourceModule === "SP_MIGRATION_READONLY") return true;
  if (voucher.voucherNumber && voucher.voucherNumber.startsWith("MIG-")) return true;
  return false;
}

export function isGoldenCoastProgrammeVoucher(voucher: GuardedVoucher) {
  if (!voucher) return false;
  return Boolean(voucher.voucherNumber && voucher.voucherNumber.startsWith("GC-"));
}

/**
 * Cash-transfer journals generated by the current Golden Coast POS settlement
 * engine. PAYABLE reclassification journals intentionally remain locked.
 */
export function isGoldenCoastPosCashSettlementVoucher(voucher: GuardedVoucher) {
  const voucherNumber = voucher?.voucherNumber || "";
  return /^GC-POS-.+-(?:create|edit\d+)-CASH(?:-HADI)?(?:-REV-\d+)?$/.test(voucherNumber);
}

/** True when the Daybook must block both edit and delete controls. */
export function isVoucherMutationBlocked(voucher: GuardedVoucher) {
  if (isReadonlyMigratedVoucher(voucher)) return true;
  if (isGoldenCoastPosCashSettlementVoucher(voucher)) return false;
  return isGoldenCoastProgrammeVoucher(voucher);
}

/** Short label for the lock badge, or null when the voucher is editable/deletable. */
export function voucherLockLabel(voucher: GuardedVoucher): string | null {
  if (isReadonlyMigratedVoucher(voucher)) return "Read-only migration";
  if (isGoldenCoastProgrammeVoucher(voucher)) return "Golden Coast posting";
  return null;
}
