version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Africa/Lubumbashi
    open-pull-requests-limit: 0
    labels:
      - dependencies
