export interface CompanyExportData {
  company: unknown;
  companySettings: unknown[];
  locations: unknown[];
  // Ledger / Finance
  ledgerAccounts: unknown[];
  bankAccounts: unknown[];
  fixedAssets: unknown[];
  exchangeRates: unknown[];
  fiscalPeriodClosures: unknown[];
  referenceSequences: unknown[];
  agentAccounts: unknown[];
  // Vouchers
  vouchers: unknown[];
  voucherEntries: unknown[];
  // Suppliers
  suppliers: unknown[];
  supplierTransactions: unknown[];
  supplierProformas: unknown[];
  supplierProformaLines: unknown[];
  supplierContainers: unknown[];
  supplierContainerLoadedItems: unknown[];
  // Customers
  customers: unknown[];
  customerTransactions: unknown[];
  customerBalances: unknown[];
  customerOrders: unknown[];
  customerOrderLines: unknown[];
  customerOrderBales: unknown[];
  customerOrderCharges: unknown[];
  customerProformas: unknown[];
  customerProformaLines: unknown[];
  creditNoteItems: unknown[];
  // Employees
  employees: unknown[];
  employeePayrolls: unknown[];
  employeePayrollItems: unknown[];
  employeeAdvances: unknown[];
  salaryAdvances: unknown[];
  salaryAdvanceDeductions: unknown[];
  employeeAdvanceRepayments: unknown[];
  employeeAttendance: unknown[];
  employeeBonuses: unknown[];
  employeeGroups: unknown[];
  employeeGroupMembers: unknown[];
  employeeBaleRates: unknown[];
  employeeBalePercentRates: unknown[];
  workerDocs: unknown[];
  // Factory Workers
  factoryWorkers: unknown[];
  factoryWorkerCategories: unknown[];
  factoryWorkerDocuments: unknown[];
  factoryWorkerAdvances: unknown[];
  factoryAdvanceRepayments: unknown[];
  factoryPayrolls: unknown[];
  factoryAttendance: unknown[];
  workerBonuses: unknown[];
  // Factory Operations
  factorySettings: unknown[];
  factoryCategories: unknown[];
  factoryDaybook: unknown[];
  factoryDaybookEdits: unknown[];
  factoryDailyKpiSnapshots: unknown[];
  factoryDailyUsages: unknown[];
  factoryAlerts: unknown[];
  factoryDutyAuditLog: unknown[];
  // Factory Raw / Production
  factoryRawStock: unknown[];
  factoryRawMaterialAdjustments: unknown[];
  factoryPressingBatches: unknown[];
  pressingBatches: unknown[];
  factoryMixBatches: unknown[];
  factoryMixBatchSources: unknown[];
  mixBatches: unknown[];
  mixBatchSources: unknown[];
  productionBales: unknown[];
  productionRawStock: unknown[];
  // Factory Bales
  factoryBaleProducts: unknown[];
  factoryBales: unknown[];
  factoryBaleSequences: unknown[];
  factoryBaleCostSnapshots: unknown[];
  factoryBaleWasteDispatches: unknown[];
  factoryWasteEntries: unknown[];
  // Factory Containers
  factoryContainers: unknown[];
  factoryContainerCommissions: unknown[];
  factoryContainerOtherCharges: unknown[];
  factoryContainerProfitSnapshots: unknown[];
  factoryOffloadAdditionalCharges: unknown[];
  // Factory Suppliers
  factorySuppliers: unknown[];
  factorySupplierPayments: unknown[];
  factorySupplierFxTransfers: unknown[];
  factorySupplierScoreSnapshots: unknown[];
  // Factory FX
  factoryFxRates: unknown[];
  factoryFxAllocations: unknown[];
  // Factory POS
  factoryPosSales: unknown[];
  factoryPosSaleItems: unknown[];
  // Bales (Sorting)
  bales: unknown[];
  baleProducts: unknown[];
  baleProductCategories: unknown[];
  baleSequences: unknown[];
  baleLabelPrints: unknown[];
  baleTransfers: unknown[];
  baleTransferItems: unknown[];
  baleRecodeSessions: unknown[];
  baleRecodeItems: unknown[];
  // Stock
  stockGroups: unknown[];
  stockItems: unknown[];
  stockItemCodeAliases: unknown[];
  stockItemLocationPrices: unknown[];
  inventory: unknown[];
  inventoryNegativeLayers: unknown[];
  stockGroupLocationArchives: unknown[];
  stockGroupLocationArchiveItems: unknown[];
  stockTransfers: unknown[];
  stockTransferItems: unknown[];
  stockTransferRevisions: unknown[];
  stockTransferRevisionItems: unknown[];
  stockAdjustments: unknown[];
  stockAdjustmentItems: unknown[];
  proformaStockReservations: unknown[];
  // Containers
  containersDetail: unknown[];
  containers: unknown[];
  containerCharges: unknown[];
  containerOffloads: unknown[];
  containerOffloadItems: unknown[];
  containerFreight: unknown[];
  containerFreightPayments: unknown[];
  containerDocuments: unknown[];
  containerSales: unknown[];
  // Purchase Orders
  purchaseOrders: unknown[];
  poLineItems: unknown[];
  // POS
  posShifts: unknown[];
  salesItems: unknown[];
  // Waste
  wasteDispatches: unknown[];
  wasteDispatchItems: unknown[];
  // Spreadsheets
  spreadsheets: unknown[];
  // Import Logs
  importLogs: unknown[];
  // Audit
  auditLog: unknown[];
  // ── Enriched / Detail Views ────────────────────────────────────────────────
  voucherLinesDetail: unknown[];
  poDetail: unknown[];
  stockTransferDetail: unknown[];
  supplierBalances: unknown[];
  supplierTxnDetail: unknown[];
  customerBalancesDetail: unknown[];
  customerOrderDetail: unknown[];
  creditNoteDetail: unknown[];
  salaryAdvancesDetail: unknown[];
  employeeTxnDetail: unknown[];
  locationStockDetail: unknown[];
  // ── Factory Enriched Detail Views ──────────────────────────────────────────
  factoryBaleDetail: unknown[];
  factoryWorkerAdvancesDetail: unknown[];
  factoryPayrollDetail: unknown[];
  factoryContainerDetail: unknown[];
  factorySupplierPaymentsDetail: unknown[];
  factoryRawStockDetail: unknown[];
  factoryMixBatchDetail: unknown[];
  factoryPosSalesDetail: unknown[];
}
