import { getErrorMessage } from "../lib/httpHandlers";
import { logger } from "../lib/logger";
/**
 * GET /api/reports/net-position-monthly-excel
 * Streams the multi-sheet workbook generated by generateNetPositionExcel().
 */

import type { Express } from "express";
import { requireAuth, requireNonPOS } from "../auth";
import { storage } from "../storage";
import { generateNetPositionExcel, generateMonthEnds } from "../helpers/generateNetPositionExcel";
import { getClientDate } from "../lib/dateUtils";
import { resolveAuthorizedCompanyId, sendCompanyAccessError } from "../security/companyAccessBoundary";

export function registerNetPositionMonthlyExcelRoute(app: Express) {
  app.get("/api/reports/net-position-monthly-excel", requireAuth, requireNonPOS, async (req, res) => {
    try {
      const companyId = await resolveAuthorizedCompanyId(req, req.query.companyId);

      const allCompanies = await storage.getAllCompanies();
      const company = allCompanies.find((candidate) => candidate.id === companyId);
      if (!company) return res.status(404).json({ message: "Company not found" });
      const companyName = company.name || "Company";

      const startDate = (req.query.startDate as string) || "";
      const endDate = (req.query.endDate as string) || getClientDate(req);
      if (!startDate) return res.status(400).json({ message: "startDate is required" });
      if (generateMonthEnds(startDate, endDate).length === 0) {
        return res.status(400).json({ message: "No months in range" });
      }

      const safeCompany = companyName.replace(/[^a-z0-9]/gi, "_");
      const safeStart = startDate.replace(/-/g, "");
      const safeEnd = endDate.replace(/-/g, "");
      res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
      res.setHeader(
        "Content-Disposition",
        `attachment; filename="NetPosition_Monthly_${safeCompany}_${safeStart}_${safeEnd}.xlsx"`
      );
      await generateNetPositionExcel(companyId, companyName, startDate, endDate, res);
      res.end();
    } catch (error: unknown) {
      logger.error("Net position monthly Excel error:", { error });
      if ((error as any)?.name === "CompanyAccessError") {
        return sendCompanyAccessError(res, error);
      }
      res.status(500).json({ message: getErrorMessage(error) });
    }
  });
}
