// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/stock-allocation/CleanStructured.tsx": () => import("../components/mockups/stock-allocation/CleanStructured.tsx"),
  "./components/mockups/stock-allocation/ModernDashboard.tsx": () => import("../components/mockups/stock-allocation/ModernDashboard.tsx")
};
