// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/SidebarCredit.tsx": () => import("../components/mockups/SidebarCredit.tsx"),
  "./components/mockups/payment-receipt/Clean.tsx": () => import("../components/mockups/payment-receipt/Clean.tsx"),
  "./components/mockups/payment-receipt/Modern.tsx": () => import("../components/mockups/payment-receipt/Modern.tsx"),
  "./components/mockups/payment-receipt/Structured.tsx": () => import("../components/mockups/payment-receipt/Structured.tsx"),
  "./components/mockups/chatbot-variants/CleanOpen.tsx": () => import("../components/mockups/chatbot-variants/CleanOpen.tsx"),
  "./components/mockups/chatbot-variants/SidePanel.tsx": () => import("../components/mockups/chatbot-variants/SidePanel.tsx"),
  "./components/mockups/chatbot-variants/SleekDark.tsx": () => import("../components/mockups/chatbot-variants/SleekDark.tsx")
};
