/**
 * Guard against editing/voiding/deleting historical vouchers that were copied in
 * read-only mode by the GC-LSHI (or any future) migration tool.
 *
 * A voucher is considered a read-only migrated voucher if either:
 *  - its sourceModule is 'SP_MIGRATION_READONLY' (new migration tool), or
 *  - its voucherNumber starts with 'MIG-' (legacy migrated vouchers created
 *    before the dedicated sourceModule value existed).
 *
 * These vouchers must never move stock again and must never be edited, voided,
 * or deleted — they exist purely as historical accounting record copies.
 */
export function isReadonlyMigratedVoucher(voucher: {
  sourceModule?: string | null;
  voucherNumber?: string | null;
}): boolean {
  if (!voucher) return false;
  if (voucher.sourceModule === "SP_MIGRATION_READONLY") return true;
  if (voucher.voucherNumber && voucher.voucherNumber.startsWith("MIG-")) return true;
  return false;
}

export const READONLY_MIGRATED_VOUCHER_MESSAGE =
  "This voucher was copied in read-only mode by the GC-LSHI migration tool and cannot be edited, voided, or deleted.";

/**
 * Golden Coast programme vouchers are generated by the central posting engine
 * from a deterministic, idempotency-tracked request: the cutover journal, POS
 * sale and settlement pairs, HADI transfers, special-location deductions,
 * container offloads, Hassan Savings withdrawals, monthly closes, and the
 * reversals of any of them. Every one of those numbers starts with "GC-".
 *
 * Hand-editing one desynchronises the balance its own route caps against — the
 * GC Sales Cash payable most of all — and leaves the stored posting-request
 * marker describing entries that no longer exist, so the next replay of the
 * same client request fails as inconsistent instead of returning the original
 * voucher. Corrections are made by posting a balanced reversal and re-posting,
 * which is how the POS edit path already works; the original document stays.
 */
export function isGoldenCoastProgrammeVoucher(voucher: { voucherNumber?: string | null }): boolean {
  return Boolean(voucher?.voucherNumber?.startsWith("GC-"));
}

export const GOLDEN_COAST_PROGRAMME_VOUCHER_MESSAGE =
  "This voucher was posted by the Golden Coast accounting programme and cannot be edited, voided, or deleted. " +
  "Correct it by reversing and re-posting through the originating workflow.";

/**
 * Single check for every voucher mutation route: returns the reason a voucher
 * may not be changed, or null when it is editable. Callers must use this rather
 * than testing one protection in isolation, so a new protected class reaches
 * every write path at once.
 */
export function voucherMutationBlockReason(voucher: {
  sourceModule?: string | null;
  voucherNumber?: string | null;
}): string | null {
  if (!voucher) return null;
  if (isReadonlyMigratedVoucher(voucher)) return READONLY_MIGRATED_VOUCHER_MESSAGE;
  if (isGoldenCoastProgrammeVoucher(voucher)) return GOLDEN_COAST_PROGRAMME_VOUCHER_MESSAGE;
  return null;
}
