import {useEffect, useState} from "react";

type Language = "en" | "ar" | "fr";

const copy = {
  en: {
    title: "Orders",
    subtitle: "Review transfers, inspect item changes, and submit revisions",
    newTransfer: "New Transfer",
    date: "Date",
    status: "Status",
    search: "Search",
    allOrders: "All orders",
    pending: "Pending",
    applied: "Applied",
    searchPlaceholder: "Voucher number or item name",
    clear: "Clear",
    loadingOrders: "Loading orders",
    order: "order",
    orders: "orders",
    noOrders: "No transfer orders found",
    clearFilters: "Clear the filters to see more orders.",
    from: "From",
    to: "To",
    item: "item",
    items: "items",
    latestRevision: "Latest: Revision",
    awaitingReview: "awaiting review",
    revision: "revision",
    revisions: "revisions",
    viewDetails: "View details",
    createRevision: "Create revision",
    transferOrder: "Transfer Order",
    loadingTransferDetails: "Loading transfer details…",
    fromLocation: "From location",
    toLocation: "To location",
    unknownSource: "Unknown source",
    unknownDestination: "Unknown destination",
    originalQuantity: "Original quantity",
    currentEffective: "Current effective",
    changedItems: "Changed items",
    transferredItems: "Transferred items",
    original: "Original",
    current: "Current",
    difference: "Difference",
    noItemLines: "No item lines were returned for this transfer.",
    revisionHistory: "Revision history",
    oldestToNewest: "Oldest to newest",
    noRevisions: "No revisions have been submitted.",
    pendingReview: "Pending review",
    approved: "Approved",
    rejected: "Rejected",
    superseded: "Superseded",
    previous: "Previous",
    revised: "Revised",
    change: "Change",
    added: "Added",
    removed: "Removed",
    increased: "Increased",
    reduced: "Reduced",
    unchanged: "Unchanged",
    failedToLoad: "Failed to load this transfer order.",
  },
  ar: {
    title: "الطلبات",
    subtitle: "راجع التحويلات وتغييرات الأصناف وأرسل المراجعات",
    newTransfer: "تحويل جديد",
    date: "التاريخ",
    status: "الحالة",
    search: "بحث",
    allOrders: "كل الطلبات",
    pending: "قيد الانتظار",
    applied: "مُطبّق",
    searchPlaceholder: "رقم السند أو اسم الصنف",
    clear: "مسح",
    loadingOrders: "جارٍ تحميل الطلبات",
    order: "طلب",
    orders: "طلبات",
    noOrders: "لا توجد طلبات تحويل",
    clearFilters: "امسح عوامل التصفية لعرض المزيد من الطلبات.",
    from: "من",
    to: "إلى",
    item: "صنف",
    items: "أصناف",
    latestRevision: "أحدث مراجعة",
    awaitingReview: "بانتظار المراجعة",
    revision: "مراجعة",
    revisions: "مراجعات",
    viewDetails: "عرض التفاصيل",
    createRevision: "إنشاء مراجعة",
    transferOrder: "أمر تحويل",
    loadingTransferDetails: "جارٍ تحميل تفاصيل التحويل…",
    fromLocation: "من الموقع",
    toLocation: "إلى الموقع",
    unknownSource: "مصدر غير معروف",
    unknownDestination: "وجهة غير معروفة",
    originalQuantity: "الكمية الأصلية",
    currentEffective: "الكمية الحالية الفعلية",
    changedItems: "الأصناف المعدلة",
    transferredItems: "الأصناف المحولة",
    original: "الأصلية",
    current: "الحالية",
    difference: "الفرق",
    noItemLines: "لم يتم العثور على بنود أصناف لهذا التحويل.",
    revisionHistory: "سجل المراجعات",
    oldestToNewest: "من الأقدم إلى الأحدث",
    noRevisions: "لم يتم إرسال أي مراجعات.",
    pendingReview: "بانتظار المراجعة",
    approved: "موافق عليها",
    rejected: "مرفوضة",
    superseded: "تم استبدالها",
    previous: "السابقة",
    revised: "المعدلة",
    change: "التغيير",
    added: "مضاف",
    removed: "محذوف",
    increased: "زيادة",
    reduced: "تخفيض",
    unchanged: "بدون تغيير",
    failedToLoad: "تعذر تحميل أمر التحويل.",
  },
  fr: {
    title: "Commandes",
    subtitle: "Consultez les transferts, les modifications d’articles et envoyez des révisions",
    newTransfer: "Nouveau transfert",
    date: "Date",
    status: "Statut",
    search: "Rechercher",
    allOrders: "Toutes les commandes",
    pending: "En attente",
    applied: "Appliqué",
    searchPlaceholder: "Numéro de pièce ou nom d’article",
    clear: "Effacer",
    loadingOrders: "Chargement des commandes",
    order: "commande",
    orders: "commandes",
    noOrders: "Aucune commande de transfert trouvée",
    clearFilters: "Effacez les filtres pour afficher plus de commandes.",
    from: "De",
    to: "À",
    item: "article",
    items: "articles",
    latestRevision: "Dernière révision",
    awaitingReview: "en attente de validation",
    revision: "révision",
    revisions: "révisions",
    viewDetails: "Voir les détails",
    createRevision: "Créer une révision",
    transferOrder: "Ordre de transfert",
    loadingTransferDetails: "Chargement des détails du transfert…",
    fromLocation: "Emplacement source",
    toLocation: "Emplacement de destination",
    unknownSource: "Source inconnue",
    unknownDestination: "Destination inconnue",
    originalQuantity: "Quantité d’origine",
    currentEffective: "Quantité effective actuelle",
    changedItems: "Articles modifiés",
    transferredItems: "Articles transférés",
    original: "Original",
    current: "Actuel",
    difference: "Différence",
    noItemLines: "Aucune ligne d’article n’a été renvoyée pour ce transfert.",
    revisionHistory: "Historique des révisions",
    oldestToNewest: "De la plus ancienne à la plus récente",
    noRevisions: "Aucune révision n’a été soumise.",
    pendingReview: "En attente de validation",
    approved: "Approuvée",
    rejected: "Rejetée",
    superseded: "Remplacée",
    previous: "Précédent",
    revised: "Révisé",
    change: "Modification",
    added: "Ajouté",
    removed: "Supprimé",
    increased: "Augmenté",
    reduced: "Réduit",
    unchanged: "Inchangé",
    failedToLoad: "Impossible de charger cet ordre de transfert.",
  },
} as const;

function readLanguage(): Language {
  const language = document.documentElement.lang.toLowerCase();
  if (language.startsWith("ar")) return "ar";
  if (language.startsWith("fr")) return "fr";
  return "en";
}

export function usePosTransferCopy() {
  const [language, setLanguage] = useState<Language>(() => readLanguage());

  useEffect(() => {
    const observer = new MutationObserver(() => setLanguage(readLanguage()));
    observer.observe(document.documentElement, {attributes: true, attributeFilter: ["lang", "dir"]});
    return () => observer.disconnect();
  }, []);

  return {language, text: copy[language], isRtl: language === "ar"};
}
