/**
 * factoryCustomersRoutes: FactoryCustomerMigration endpoints.
 *
 * Registered by ./index.ts in the original order; Express resolves
 * first-match, so that order is behaviour.
 */
import type { Express } from "express";
import { getErrorMessage } from "../../../lib/httpHandlers";
import { logger } from "../../../lib/logger";
import { db } from "../../../db";
import { requireAuth } from "../../../auth";
import { customerOrders, voucherEntries, vouchers } from "@shared/schema";
import { eq, and, sql } from "drizzle-orm";

export function registerFactoryCustomerMigrationRoutes(app: Express) {
  // ─── One-time migration: fix charge descriptions & payment narrations ───────
  app.post("/api/factory/migrate-voucher-descriptions", requireAuth, async (req: any, res: any) => {
    try {
      const companyId = (req.session as any).factoryCompanyId || (req.session as any).currentCompanyId;
      if (!companyId) return res.status(400).json({ message: "No company selected" });

      let chargesFixed = 0;
      let narrationFixed = 0;

      // 1. Fix CHARGE-* vouchers: replace "ChargeName - INV-XXXXXX" with
      //    "ChargeName for offloaded container - ContainerNumber"
      const chargeVouchers = await db
        .select({ id: vouchers.id, description: vouchers.description, voucherNumber: vouchers.voucherNumber })
        .from(vouchers)
        .where(
          and(
            eq(vouchers.companyId, companyId),
            sql`${vouchers.voucherNumber} LIKE 'CHARGE-INV-%'`,
            sql`${vouchers.description} IS NOT NULL`
          )
        );

      for (const v of chargeVouchers) {
        // Extract invoice number: voucherNumber = CHARGE-INV-XXXXXX-chargeId-timestamp
        const parts = (v.voucherNumber || "").split("-");
        // Format: CHARGE, INV, 011831, <chargeId>, <timestamp>
        const invoiceNumber = parts.length >= 3 ? `INV-${parts[2]}` : null;
        if (!invoiceNumber) continue;

        // Look up the order by invoice number
        const [order] = await db
          .select({ id: customerOrders.id, containerNumber: customerOrders.containerNumber })
          .from(customerOrders)
          .where(and(eq(customerOrders.companyId, companyId), eq(customerOrders.invoiceNumber, invoiceNumber)));

        if (!order?.containerNumber) continue;

        // Determine the charge name from description: "ChargeName - INV-XXXXXX"
        const descParts = (v.description || "").split(` - ${invoiceNumber}`);
        const chargeName = descParts[0] || v.description || "";
        const newDesc = `${chargeName} for offloaded container - ${order.containerNumber}`;

        await db.update(vouchers).set({ description: newDesc }).where(eq(vouchers.id, v.id));
        await db.update(voucherEntries).set({ narration: newDesc }).where(eq(voucherEntries.voucherId, v.id));
        chargesFixed++;
      }

      // 2. Fix Payment/Receipt/Journal narrations: set narration = voucher.description
      //    only where the voucher has a description and narration looks auto-generated
      const manualVouchers = await db
        .select({ id: vouchers.id, description: vouchers.description, voucherType: vouchers.voucherType })
        .from(vouchers)
        .where(
          and(
            eq(vouchers.companyId, companyId),
            sql`${vouchers.description} IS NOT NULL AND ${vouchers.description} != ''`,
            sql`${vouchers.voucherType} IN ('Payment', 'Receipt', 'Journal')`,
            sql`${vouchers.voucherNumber} NOT LIKE 'CHARGE-%'`,
            sql`${vouchers.voucherNumber} NOT LIKE 'FACTORY-%'`,
            sql`${vouchers.voucherNumber} NOT LIKE 'FPOS-%'`,
            sql`${vouchers.sourceModule} = 'FACTORY' OR ${vouchers.sourceModule} IS NULL`
          )
        );

      for (const v of manualVouchers) {
        const entries = await db
          .select({ id: voucherEntries.id, narration: voucherEntries.narration })
          .from(voucherEntries)
          .where(eq(voucherEntries.voucherId, v.id));

        for (const entry of entries) {
          const narr = entry.narration || "";
          // Only update if it looks like an auto-generated narration
          const isAutoGenerated =
            narr.startsWith(`${v.voucherType} - `) ||
            narr.startsWith("Payment - ") ||
            narr.startsWith("Receipt - ") ||
            narr.startsWith("Journal - ") ||
            narr === "";

          if (isAutoGenerated) {
            await db.update(voucherEntries).set({ narration: v.description }).where(eq(voucherEntries.id, entry.id));
            narrationFixed++;
          }
        }
      }

      res.json({ message: "Migration complete", chargesFixed, narrationFixed });
    } catch (error: unknown) {
      logger.error("Migration error:", { error: error });
      res.status(500).json({ message: getErrorMessage(error) });
    }
  });
}
